---
# Ansible Galaxy requirements
# 如果需要从 Galaxy 安装此 role：
# ansible-galaxy install -r requirements.yml

roles:
  - name: influx2tsdb-proxy
    src: https://github.com/mars-base/influx2tsdb-proxy.git
    version: main
    scm: git
