---
- name: Restart influx2tsdb-proxy instances
  ansible.builtin.shell: >
    supervisorctl reread &&
    supervisorctl update &&
    supervisorctl restart influx2tsdb-proxy:* || supervisorctl start influx2tsdb-proxy:*
  listen: "restart influx2tsdb-proxy instances"
